title: Arctos Alliance
email: info@arctosalliance.org
description: >- # this means to ignore newlines until "baseurl:"
  We are a collection of companies that seek to provide financial support to Arrow Apache contributors.
baseurl: "/"
url: "https://arctosalliance.org"
github_username:  arctosalliance

# Build settings
theme: minima

minima:
  skin: solarized-light
